### ISSUE TITLE
Graphite-web whisper module not found when loading renders on Ubuntu 12/14

### ISSUE THREAD

**Issue by sedan07** [gds-operations/puppet-graphite#38]
**Created using:**
Host: precise64 (Using Vagrantfile `vagrant up`)
Puppet (v2.7.19):
* puppetlabs-stdlib (v4.5.1)
* stankevich-python (v1.8.3)
* puppet-graphite (master && v2.0.2)

Receiving the following error from requests to:

```
http://GRAPHITE-HOST/render/?width=586&height=308&_salt=1423489320.156
```
OR
```
http://GRAPHITE-HOST/metrics/find/?_dc=1423489528351&query=*&format=treejson&contexts=1&path=&node=GraphiteTree
```
Error:
```
Traceback (most recent call last):
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 209, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 216, in callback
    self._callback = get_callable(self._callback_str)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/utils/functional.py", line 27, in wrapper
    result = func(*args)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 92, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "/var/lib/graphite/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/graphite/webapp/graphite/render/views.py", line 36, in <module>
    from graphite.render.evaluator import evaluateTarget
  File "/var/lib/graphite/webapp/graphite/render/evaluator.py", line 5, in <module>
    from graphite.render.datalib import fetchData, TimeSeries
  File "/var/lib/graphite/webapp/graphite/render/datalib.py", line 20, in <module>
    from graphite.storage import STORE, LOCAL_STORE
  File "/var/lib/graphite/webapp/graphite/storage.py", line 4, in <module>
    import whisper
ImportError: No module named whisper
```

Also able to recreate on a Ubuntu 14.04 host again with module config defaults using puppet 3.x

**Comment by deanwilson** [comment]
Apologies for the _quite_ large delay in responding to this issue. Due to the version bumps and changes in pretty much every part of this tool chain I'm going to mark this as closed. If it is still an issue can you please reopen with the current versions you are having issues with so we can try and diagnose.

Again, apologies.
